/* Generated By:JavaCC: Do not edit this line. HtmlParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface HtmlParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ALPHANUMERIC = 3;
  /** RegularExpression Id. */
  int QUOTE = 4;
  /** RegularExpression Id. */
  int AND = 5;
  /** RegularExpression Id. */
  int END = 6;
  /** RegularExpression Id. */
  int LINE = 7;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\t\"",
    "\"\\r\"",
    "<ALPHANUMERIC>",
    "\"\\\"\"",
    "\" AND \"",
    "\"exit\"",
    "\"\\n\"",
    "\"ADD \"",
    "\"IMAGE WITH SOURCE \"",
    "\"HEADING \"",
    "\"PARAGRAPH \"",
    "\"WITH \"",
    "\"LINK \"",
    "\"TEXT \"",
    "\"COLOR \"",
    "\"FONT \"",
  };

}
